# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Geometry-Voronoi
version:      1.1
version_from: lib/Math/Geometry/Voronoi.pm
installdirs:  site
requires:
    Class::Accessor:               0
    List::Util:                    0
    Params::Validate:              0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
